Repository Lothrazar/Cyclic, pull requests merged in 2022-02, with the labels that each got.

#2011 Invalidate capabilities when declaring them
  src/main/java/com/lothrazar/cyclic/block/anvil/TileAnvilAuto.java
  src/main/java/com/lothrazar/cyclic/block/anvilmagma/TileAnvilMagma.java
  src/main/java/com/lothrazar/cyclic/block/anvilvoid/TileAnvilVoid.java
  src/main/java/com/lothrazar/cyclic/block/battery/TileBattery.java
  src/main/java/com/lothrazar/cyclic/block/beaconpotion/TilePotion.java
  src/main/java/com/lothrazar/cyclic/block/cable/CableBase.java
  src/main/java/com/lothrazar/cyclic/block/cable/TileCableBase.java
  src/main/java/com/lothrazar/cyclic/block/cable/energy/BlockCableEnergy.java
  src/main/java/com/lothrazar/cyclic/block/cable/energy/TileCableEnergy.java
  src/main/java/com/lothrazar/cyclic/block/cable/fluid/BlockCableFluid.java
  src/main/java/com/lothrazar/cyclic/block/cable/fluid/TileCableFluid.java
  src/main/java/com/lothrazar/cyclic/block/cable/item/BlockCableItem.java
  src/main/java/com/lothrazar/cyclic/block/cable/item/TileCableItem.java
  src/main/java/com/lothrazar/cyclic/block/collectfluid/TileFluidCollect.java
  src/main/java/com/lothrazar/cyclic/block/collectitem/TileItemCollector.java
  src/main/java/com/lothrazar/cyclic/block/crafter/TileCrafter.java
  src/main/java/com/lothrazar/cyclic/block/crate/TileCrate.java
  src/main/java/com/lothrazar/cyclic/block/creativebattery/TileBatteryInfinite.java
  src/main/java/com/lothrazar/cyclic/block/creativeitem/TileItemInfinite.java
  src/main/java/com/lothrazar/cyclic/block/disenchant/TileDisenchant.java
  src/main/java/com/lothrazar/cyclic/block/dropper/TileDropper.java
  src/main/java/com/lothrazar/cyclic/block/enderctrl/TileEnderCtrl.java
  src/main/java/com/lothrazar/cyclic/block/enderitemshelf/TileItemShelf.java
  src/main/java/com/lothrazar/cyclic/block/endershelf/TileEnderShelf.java
  src/main/java/com/lothrazar/cyclic/block/expcollect/TileExpPylon.java
  src/main/java/com/lothrazar/cyclic/block/fishing/TileFisher.java
  src/main/java/com/lothrazar/cyclic/block/forester/TileForester.java
  src/main/java/com/lothrazar/cyclic/block/generatorfluid/TileGeneratorFluid.java
  src/main/java/com/lothrazar/cyclic/block/generatorfood/TileGeneratorFood.java
  src/main/java/com/lothrazar/cyclic/block/generatorfuel/TileGeneratorFuel.java
  src/main/java/com/lothrazar/cyclic/block/generatoritem/TileGeneratorDrops.java
  src/main/java/com/lothrazar/cyclic/block/generatorpeat/TileGeneratorPeat.java
  src/main/java/com/lothrazar/cyclic/block/harvester/TileHarvester.java
  src/main/java/com/lothrazar/cyclic/block/hopper/TileSimpleHopper.java
  src/main/java/com/lothrazar/cyclic/block/hopperfluid/TileFluidHopper.java
  src/main/java/com/lothrazar/cyclic/block/laser/TileLaser.java
  src/main/java/com/lothrazar/cyclic/block/lightcompr/TileLightCamo.java
  src/main/java/com/lothrazar/cyclic/block/melter/TileMelter.java
  src/main/java/com/lothrazar/cyclic/block/miner/TileMiner.java
  src/main/java/com/lothrazar/cyclic/block/packager/TilePackager.java
  src/main/java/com/lothrazar/cyclic/block/peatfarm/TilePeatFarm.java
  src/main/java/com/lothrazar/cyclic/block/placer/TilePlacer.java
  src/main/java/com/lothrazar/cyclic/block/placerfluid/TilePlacerFluid.java
  src/main/java/com/lothrazar/cyclic/block/shapebuilder/TileStructure.java
  src/main/java/com/lothrazar/cyclic/block/shapedata/TileShapedata.java
  src/main/java/com/lothrazar/cyclic/block/solidifier/TileSolidifier.java
  src/main/java/com/lothrazar/cyclic/block/soundmuff/ghost/SoundmuffTile.java
  src/main/java/com/lothrazar/cyclic/block/soundplay/TileSoundPlayer.java
  src/main/java/com/lothrazar/cyclic/block/soundrecord/TileSoundRecorder.java
  src/main/java/com/lothrazar/cyclic/block/sprinkler/TileSprinkler.java
  src/main/java/com/lothrazar/cyclic/block/tank/TileTank.java
  src/main/java/com/lothrazar/cyclic/block/tankcask/TileCask.java
  src/main/java/com/lothrazar/cyclic/block/trash/TileTrash.java
  src/main/java/com/lothrazar/cyclic/block/uncrafter/TileUncraft.java
  src/main/java/com/lothrazar/cyclic/block/user/TileUser.java
  src/main/java/com/lothrazar/cyclic/block/wireless/energy/TileWirelessEnergy.java
  src/main/java/com/lothrazar/cyclic/block/wireless/fluid/TileWirelessFluid.java
  src/main/java/com/lothrazar/cyclic/block/wireless/item/TileWirelessItem.java
  src/main/java/com/lothrazar/cyclic/block/wireless/redstone/TileWirelessTransmit.java
Labels: 1.16

#2013 Add caching of packager recipes and move static methods out of main class for scaling
  src/main/java/com/lothrazar/cyclic/block/packager/TilePackager.java
  src/main/java/com/lothrazar/cyclic/block/packager/UtilPackager.java
  src/main/java/com/lothrazar/cyclic/compat/jei/PackagerRecipeCategory.java
Labels: 1.16

#1900 Improve UtilString.isInList performance
  src/main/java/com/lothrazar/cyclicmagic/block/autouser/TileEntityUser.java
  src/main/java/com/lothrazar/cyclicmagic/item/mobcapture/EntityMagicNetEmpty.java
  src/main/java/com/lothrazar/cyclicmagic/item/mobcapture/ItemProjectileMagicNet.java
  src/main/java/com/lothrazar/cyclicmagic/item/tiletransporter/ItemChestSackEmpty.java
  src/main/java/com/lothrazar/cyclicmagic/util/UtilHarvester.java
  src/main/java/com/lothrazar/cyclicmagic/util/UtilRepairItem.java
  src/main/java/com/lothrazar/cyclicmagic/util/UtilScythe.java
  src/main/java/com/lothrazar/cyclicmagic/util/UtilString.java
Labels: 1.12

#1879 Check if fluids exist before adding melter recipe
  src/main/java/com/lothrazar/cyclicmagic/block/melter/RecipeMelter.java
  src/main/java/com/lothrazar/cyclicmagic/block/solidifier/RecipeSolidifier.java
Labels: 1.12

#2035 Add config values for terra preta
  src/main/java/com/lothrazar/cyclic/block/terraglass/TileTerraGlass.java
  src/main/java/com/lothrazar/cyclic/block/terrasoil/TileTerraPreta.java
  src/main/java/com/lothrazar/cyclic/config/ConfigRegistry.java
Labels: 1.18
